### ISSUE TITLE
Bug Found - Sytnax Error

### ISSUE THREAD

**Issue by anieve01** [danilop/serverless-positive-chat#4]
A comma is missing between 'hi' and 'ja' below which is causing the chat app to not work.

const DETECT_SENTIMENT_LANGUAGES = [
    'en', 'es', 'fr', 'de', 'it', 'pt',
    'ar', 'hi' 'ja', 'ko', 'zh', 'zh-TW'
];

**Comment by danilop** [comment]
Solved, thanks for spotting!

**Comment by anieve01** [comment]
Thanks!
